### PR TITLE
Fix comments with no likes that displayed 1 like

### PR DESCRIPTION
**Pull request by Synkky**
This fixes FreeTubeApp/FreeTube#627

### CODE REVIEW

**Comment by Synkky** [comment]
I also have a more readable solution with nullish coalescent operator if you prefer that (does this PR stay ok if I git push --force to replace this commit? I've never tried that before)

**Comment by PrestonN** [comment]
Yes, your PR will still be here if you force push.

**Comment by Synkky** [comment]
Because I'm an idiot and failed to notice some things, I had to do that multiple times. Sorry about that.

**Comment by GilgusMaximus** [comment]
Does that code run for you ? When I try to execute scrape_next_page_youtube_comments() it says "Unexpected token '.'" after the first question mark.

**Comment by GilgusMaximus** [comment]
Sorry but i did not get that code to run. I created my own fix for that.
But anyway thanks for the contribution and showing me where the problem lies 👍

**Comment by Synkky** [comment]
This was my bad, because I used Node 14 to test instead of 12, didn't notice at all.

**Comment by GilgusMaximus** [comment]
oh yeah. That is the issue I think. That is my bad, I should have listed my NodeJS version.
Yes that is true. It doesn't make a difference I think, but I will change it :)

**Pull request closed without merging**
