### PR TITLE
fix error when channel owner hides user from channel.

### PR DESCRIPTION
**Pull request by maykbrito**
Scenario:

* Channel owner hide user from channel
* YouTube system will hide comments by that user

When that happens, user's comments will not be fetched and will be unavailable witch cause unexpected error. 

This bug fix will skip that comment.

### CODE REVIEW

**Review by GilgusMaximus — CHANGES_REQUESTED** [review]
So first of all, thanks for the contribution, it is always nice to see other people improving my code.

While this change is definitely useful, it is only in the extractCommentRepliesFromJSON() function and not in the extractCommentHtmlEntries() function, which is a bit irritating because I would assume a hidden channel can occur as a normal comment as well. (Correct me if I am wrong here). In that case, it would be required to add the same code to the function above.

However this only catches these 3 problems. If we want to make this more future safe, I would suggest removing this and adding a try catch block to both functions, which catch any missing item. The reason for this is that in case of a change from YouTube in their internal layout, the module will break if it doesn't appear in the commentEntry or the children you covered. So a try catch with a meaningful error message will be more future proof and all users can then see what kind of error occurs in order to report the issue.

So if you could make these changes I'll approve the PR :) 

Best regards,
GilgusMaximus

**Comment by maykbrito** [comment]
Thanks for instructions. 😍
I'll do that!

**Comment by GilgusMaximus** [comment]
Thanks a lot for the changes.
I tested a few videos and it looks good to me.
Therefore I am gonna merge this and push the newest version to NPM.

**Review by GilgusMaximus — APPROVED** [review]
Code works fine and looks good

**Pull request merged**
